services:
  api:
    build: .
    container_name: image-dispatch-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: image-dispatch-db
    environment:
      POSTGRES_DB: image_dispatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
